---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
      infisical:
        auth:
          universalAuthCredentials:
            clientId:
              key: clientId
              namespace: external-secrets
              name: infisical-secret 
            clientSecret:
              key: clientSecret
              namespace: external-secrets
              name: infisical-secret
        secretsScope:
          projectSlug: automation-ek-ae
          environmentSlug: prod
          secretsPath: /apps
          recursive: true
          expandSecretReferences: false
        hostAPI: https://eu.infisical.com