apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:xqLOu18UaaeJiYMa/+OSCgsDN95cedFuadWHa4udrG4a+eQ7F2ykNAsNaQZJZtcDGP8mXHImJuy5S9aCWzSyhuWJLE0rQKVqvrg=,iv:XyG/+knU8lqWuPzCIfh8X725VVgFA+/qP9pL3Ng8lyg=,tag:QfF4c7hYC8sXcRWHn08HPg==,type:str]
sops:
    age:
        - recipient: age14c5pysj06j6dd5wpvmxh05gsgmvj0gm27qfrelhj8decavrlkuus95lcmu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR1dRN2NBc1EycUllVnF3
            RXhjdW54bDBzczZ6VW9NQ3BTbEw4R1ZZUjBBCjNZalZnaWZ6VHRuaDYyQTl1dEl0
            UjNCK0tLaWJ4S2E0UlgveTNoQU8wR00KLS0tIEMzNXUwSzdhczZlN21UU2FWdWIy
            WGdhVUhKd0JtQ0sySFF2OHZSaUsxVkEKXoyYu7Q66WCQ+YaswRA3hve007zEYnX1
            gnlk4dROlwNH2b2p78CohoSv/CiMm9Wm/+DgKf8wO/xk3a+iidLdyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n50gn375hw4zldle7s4w00zqa9htwrg3eq2jxnn3g57pjcutw5uqxwdnqn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcTRDeDBYSTQ0VDd4Q2U4
            US9oT01qSEZMUmZYTElrdXRTY0RGQmZFVlNjCnhuL254amlHa1ZRNUNFOTdHTjJM
            cnkwN2xtb1JlTTRJdTJoU1NRVjlTLzgKLS0tIFYxRkdFNmpvcW9YSXFyellIQVd2
            TVYwU2krbTA2WVhqc2dOaGd4RVYzV2sK1LBounlR3hKOsbN5h1n0q4DHOxo2KoVi
            Q0gQ3KroYhPSj29mqqctR3Xs2LKcscbT4AM6ndIBN7OdS8/yPCozug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-12T20:06:17Z"
    mac: ENC[AES256_GCM,data:EePGEzgXZb4K4yDw8WRcVo4SKmiVf2TkU/nQY+32ya7teE4Haezs4mhJbvDFojsH5Q0RcN18U+4COVr+NKKNw/d/Adm03rxHm0a56UZlWaHDLce4DtF624rrutlVDzc9Z2ZH1gSlAHn7ddRLtDxd7TxyTDW6pGzmWIxh2cTH9fk=,iv:P7FYQAyOSaTmA9R0wyfYqL51doutl9+NYYZ576W/Y9Y=,tag:ndo3WZIhSK243pR1/DmhRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
